apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  DB_POSTGRESDB_PASSWORD: "supersecurepass"
  N8N_BASIC_AUTH_PASSWORD: "supersecurepass"
  N8N_ENCRYPTION_KEY: "claveky"
